services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 4000:80

  dev:
    extends: app
    build:
      target: dev
    volumes:
      - ./bin:/app/bin
      - ./projects:/app/projects
      - ./public:/app/public
      - ./src:/app/src
      - ./vite-plugin-project-builder:/app/vite-plugin-project-builder
      - ./index.html:/app/index.html
      - ./projects.schema.json:/app/projects.schema.json
      - ./vite.config.ts:/app/vite.config.ts
      - ./vite.config.server.ts:/app/vite.config.server.ts
