services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 4000:80

  dev:
    extends: app
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./projects:/app/projects
      - ./public:/app/public
      - ./src:/app/src
      - ./vite-plugin-project-builder:/app/vite-plugin-project-builder
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.node.json:/app/tsconfig.node.json
