name: Add a Project
description: Request to have a new project added to Inexorable Fate
title: "Add <project name>"
labels: ["project add"]
body:
  - type: input
    id: project-name
    attributes:
      label: Project Name
    validations:
      required: true
  - type: input
    id: author
    attributes:
      label: Author(s)
  - type: dropdown
    id: self-sumbitted
    attributes:
      label: Are you the creator of this project?
      description: It’s fine if you’re not!
      options:
        - "Yes"
        - "No"
  - type: dropdown
    id: final
    attributes:
      label: Has the project been verified by the creator as finalized and ready for print and play?
      description: Note that we generally only include finalized projects on Inexorable Fate. But if the project you’re requesting is not yet ready, we’ll try to keep an eye out for it.
      options:
        - "Yes"
        - "No"
        - Not Sure
  - type: input
    id: cards-link
    attributes:
      label: Link to cards
  - type: input
    id: website
    attributes:
      label: Link to a web page with more details about this project
      description: Can be the author’s website, a page on Mysterious Chanting or Arkham Central, or a post on Reddit or BGG
  - type: checkboxes
    id: tags
    attributes:
      label: What’s included in this project?
      description: Select all that apply
      options:
        - label: Campaign
        - label: Standalone scenario
        - label: Investigator(s) & signatures
        - label: Player Cards
        - label: Add-Ons (utility cards and other extras that don’t fall into one of the above categories)
  - type: textarea
    id: blurb
    attributes:
      label: Short teaser for the project
      description: Roughly 250 characters, definitely no more than 400.
  - type: textarea
    id: artwork
    attributes:
      label: Cover Art
      description: |
        Please upload the cover image for this project (art only, no card or box frame).
        We will crop it to 1180px by 500px, so please make sure you choose an image that will work in this horizontal format.
        Attach it by clicking this area to highlight it and then dragging the image in.
  - type: textarea
    id: eons
    attributes:
      label: Strange Eons Project
      description: |
        Will you contribute your Strange Eons project files to the repository used by Inexorable Fate, arkham.build, and TTS?
        This repository allows us to ensure that project files are cleaned up and standardized to meet the needs of all three platforms.
        For our part, Inexorable Fate will work to ensure prints of your project are of the highest quality.
        Note that if you want to make future changes to your project (including uploading to TTS), we request that you retrieve our 
        copy of the SE files and provide us with an updated copy when you are finished.
        To share, please compress copy of your entire project, including art (but not cards that ended up being cut from the project).
        [Upload the file to our drive](https://drive.google.com/drive/folders/1U7eooy6b_n8DTA3KqbgzSkOZLky7FZTI?usp=sharing) or provide a link where we can download it.
        Please let us know if you have questions.
  - type: textarea
    id: details
    attributes:
      label: Additional details
      description: What else should we know about this project?
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you or the author if we need more info?
      placeholder: ex. discord username, email@example.com, etc.
    validations:
      required: false
