name: Add a Project
description: Request to have a new project added to Inexorable Fate
title: "[Project Add]: "
labels: ["project"]
body:
  - type: input
    id: project-name
    attributes:
      label: Project Name
    validations:
      required: true
  - type: input
    id: author
    attributes:
      label: Author(s)
  - type: dropdown
    id: self-sumbitted
    attributes:
      label: Are you the creator of this project?
      description: It’s fine if you’re not!
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: dropdown
    id: final
    attributes:
      label: Has the project been verified by the creator as finalized and ready for print and play?
      description: Note that we generally only include finalized projects on Inexorable Fate. But if the project you’re requesting is not yet ready, we’ll try to keep an eye out for it.
      options:
        - "Yes"
        - "No"
        - Not Sure
    validations:
      required: true
  - type: input
    id: cards-link
    attributes:
      label: Link to cards
  - type: input
    id: website
    attributes:
      label: Link to a web page with more details about this project
      description: Can be the author’s website, a page on Mysterious Chanting or Arkham Central, or a post on Reddit or BGG
  - type: checkboxes
    id: tags
    attributes:
      label: What’s included in this project?
      description: Select all that apply
      options:
        - label: Campaign
        - label: Standalone scenario
        - label: Investigator(s) & signatures
        - label: Player Cards
        - label: Add-Ons (utility cards and other extras that don’t fall into one of the above categories)
  - type: textarea
    id: details
    attributes:
      label: Additional details
      description: |
        What else should we know about this project?
        If you have a cover image for the project, you can attach it by clicking this area to highlight it and then dragging the image in.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. discord username, email@example.com, etc.
    validations:
      required: false
