name: Feature request
description: Suggest an idea for this project
title: "[FR]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when...
  - type: textarea
    id: fr-solution
    attributes:
      label: Describe the solution you’d like
      description: A clear and concise description of what you want to happen.
  - type: textarea
    id: fr-alt
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: addl
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. discord username, email@example.com, etc.
    validations:
      required: false
